### ISSUE TITLE
Vkontakte not working

### ISSUE THREAD

**Issue by droganov** [Sitebase/react-avatar#146]
On example page:

![image](https://user-images.githubusercontent.com/1375299/49818132-fd2d9980-fd82-11e8-9f69-4a5090d339ae.png)

Locally same picture is rendered fo every VK ID

**Comment by JorgenEvens** [comment]
Vkontakte requires an access_token since April 2017[[1]](https://vk.com/dev/service_token) so our old avatar source implementation broke. I've added a source using [Avatar Redirect](https://github.com/jorgenevens/avatar-redirect), for more information on usage please see the [readme](https://github.com/sitebase/react-avatar#avatar-redirect).

**Comment by JorgenEvens** [comment]
This has been fixed in version [v3.5.0](https://github.com/Sitebase/react-avatar/releases/tag/v3.5.0)!
