### ISSUE TITLE
Use same background color for same initials

### ISSUE THREAD

**Issue by mdocter** [Sitebase/react-avatar#16]
Hi Wim, thank you for this great React component. Very handy and useful!
But I have a question. When I set the name property with my name 'Maarten Docter' as value, I get a nice avatar displaying my initials 'MD', which is great! Except the background coloring is random. 
When I repeat this Avatar three times on the same page, I get three different background colors. Which can confuse an user, because they imply to be three different individuals instead of the same person.
Is there a smart way to get the same colors when initials are the same? Or do I need to calculate my own color hex based on some hash of the name or something?
Thanks for your reply.

Maarten

**Comment by Sitebase** [comment]
Hi Maarten,

For the moment there is not an easy solution for this. So I think, like you suggested, it would be best to calculate the hex color based on the user information.

It wouldn't be to hard for me to add this functionality to the component but don't think this is a worth the extra code. For example if you would only use first names as `name` property. And you would have 2 users with the name `John`, they would get the same color. Which is also strange because they are different users.

There are probably more of these strange edge cases where you don't want this.

An other solution is to make a composite component that wraps my avatar component, this way you can add the smarts in your own component.

**Comment by mdocter** [comment]
Hi Wim, thank you for taking a look at the possibilities. I think I will go for the composite component pattern you suggested.
Have a great weekend!
