### ISSUE TITLE
Legacy context API has been detected within a strict-mode tree

### ISSUE THREAD

**Issue by stahlmanDesign** [Sitebase/react-avatar#186]
```Warning: Legacy context API has been detected within a strict-mode tree.

The old API will be supported in all 16.x releases, but applications using it should migrate to the new version.

Please update the following components: withAvatarConfig

Learn more about this warning here: https://fb.me/react-legacy-context
```
I saw in issue https://github.com/Sitebase/react-avatar/issues/170 you were still supporting React 15.6, so I understand you can't fix this just yet. This warning indicates react-avatar will not be compatible with React 17.x

**Comment by JorgenEvens** [comment]
Hi @stahlmanDesign ,

The legacy context is still in there to support old version of React. However, when available the new context API will be used, so apart from the warning you should be fine.

Did you run into any actual issues due to this or were you just bringing the warning to my attention?

https://github.com/Sitebase/react-avatar/blob/98e982db333006fafe34ddd3366a14cc4b0459e0/src/context.js#L16-L26

**Comment by stahlmanDesign** [comment]
> Did you run into any actual issues due to this or were you just bringing the warning to my attention?
> 
No problems, just bringing it to your attention for the future, thanks

**Comment by JorgenEvens** [comment]
Hi @stahlmanDesign,

I've just released version [v3.9.4](https://github.com/Sitebase/react-avatar/releases/tag/v3.9.4) which only applies the legacy API after detecting whether the new context is available. The React warnings you've reported should no longer be shown after upgrading `react-avatar`.

**Comment by Muneem** [comment]
Perfect. Now we are not getting warning about it

**Comment by JorgenEvens** [comment]
@Muneem Great! Thanks for confirming this fixes the issue.
