### ISSUE TITLE
Setting the height

### ISSUE THREAD

**Issue by franciscop** [Sitebase/react-avatar#26]
When trying to set the `size`, it gets treated as a string instead of an int for setting the line-height:

```js
<Avatar size="40" />
```

Then the size when inspecting is `404px`. Which comes from:

```js
lineHeight: (this.props.size + Math.floor(this.props.size/10)) + 'px',
```

This works though it's not in the documentation:

```js
<Avatar size={40} />
```

A suggested solution:

```js
lineHeight: (parseInt(this.props.size) + Math.floor(this.props.size/10)) + 'px';
```

**Comment by Sitebase** [comment]
Normally you should get an error about this in your console because the `size` property is of type `number` which doesn't accept strings.

It's possible that in the current avatar component that's less clear because it's using an older version of ReactJS that still uses warning instead of errors to report problems.

In the new version I'm working on you get an error if you try to pass a string.
For example:

![screenshot 2016-05-14 11 10 56](https://cloud.githubusercontent.com/assets/421104/15267515/ed22ccda-19c4-11e6-9527-0d405c9cce1e.jpg)
